require("neovim-config.keymaps")
require("neovim-config.packer")
require("plugins-config.lualine")
require("plugins-config.catppuccin")
require("plugins-config.treesitter")
require("plugins-config.lsp-zero")
require("plugins-config.telescope")
require("plugins-config.comment")
